const char www_sensorinfo_html_array[] = 
	"<script>\n"
	"        $(document).ready(function () {\n"
	"            ReloadData()\n"
	"            setInterval(function () { ReloadData() }, 5000);\n"
	"        });\n"
	"        function ReloadData() {\n"
	"            $(\"#temperature\").load(\"/temperature.var\", function () { });\n"
	"            $(\"#humidity\").load(\"/humidity.var\", function () { });\n"
	"        }\n"
	"</script>\n"
	"<div class=\"u-full-width column\" style=\"margin-top: 5%\">\n"
	"    <h5>Sensor information</h5>\n"
	"    <table width=\"90%\">\n"
	"        <tbody>\n"
	"            <tr>\n"
	"                <td>Temperature</td>\n"
	"                <td width=\"30%\"><h4><div id=\"temperature\" align=\"right\">N/A</div></h4></td>\n"
	"            </tr>\n"
	"            <tr>\n"
	"                <td>Humidity</td>\n"
	"                <td><h4><div id=\"humidity\" align=\"right\">N/A</div></h4></td>\n"
	"            </tr>\n"
	"        </tbody>\n"
	"    </table>\n"
	"</div>\n";
const int www_sensorinfo_html_length = 814;
