const char www_settings_html_array[] = 
	"<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n"
	"<script>\n"
	"    $(document).ready(function () {\n"
	"        ReloadData()\n"
	"        setInterval(function () { ReloadData() }, 5000);\n"
	"    });\n"
	"    function ReloadData() {\n"
	"        $(\"#temperature\").load(\"/temperature.var\", function () { });\n"
	"        $(\"#humidity\").load(\"/humidity.var\", function () { });\n"
	"    }\n"
	"</script>\n"
	"\n"
	"<div class=\"u-full-width column\" style=\"margin-top: 5%\">\n"
	"    <h5>Settings</h5>\n"
	"    <table width=\"90%\">\n"
	"        <tbody>\n"
	"            <tr>\n"
	"                <td>Update Interval</td>\n"
	"            </tr>\n"
	"            <tr>\n"
	"                <td>Publish</td>\n"
	"            </tr>\n"
	"        </tbody>\n"
	"    </table>\n"
	"</div>\n";
const int www_settings_html_length = 688;
