const char www_skeleton_css_array[] = 
	"/*\n"
	"* Skeleton V2.0.4\n"
	"* Copyright 2014, Dave Gamache\n"
	"* www.getskeleton.com\n"
	"* Free to use under the MIT license.\n"
	"* http://www.opensource.org/licenses/mit-license.php\n"
	"* 12/29/2014\n"
	"*/\n"
	"\n"
	"\n"
	"/* Table of contents\n"
	"??????????????????????????????????????????????????\n"
	"- Grid\n"
	"- Base Styles\n"
	"- Typography\n"
	"- Links\n"
	"- Buttons\n"
	"- Forms\n"
	"- Lists\n"
	"- Code\n"
	"- Tables\n"
	"- Spacing\n"
	"- Utilities\n"
	"- Clearing\n"
	"- Media Queries\n"
	"*/\n"
	"\n"
	"\n"
	"/* Grid\n"
	"?????????????????????????????????????????????????? */\n"
	".container {\n"
	"  position: relative;\n"
	"  width: 100%;\n"
	"  max-width: 960px;\n"
	"  margin: 0 auto;\n"
	"  padding: 0 20px;\n"
	"  box-sizing: border-box; }\n"
	".column,\n"
	".columns {\n"
	"  width: 100%;\n"
	"  float: left;\n"
	"  box-sizing: border-box; }\n"
	"\n"
	"/* For devices larger than 400px */\n"
	"@media (min-width: 400px) {\n"
	"  .container {\n"
	"    width: 85%;\n"
	"    padding: 0; }\n"
	"}\n"
	"\n"
	"/* For devices larger than 550px */\n"
	"@media (min-width: 550px) {\n"
	"  .container {\n"
	"    width: 80%; }\n"
	"  .column,\n"
	"  .columns {\n"
	"    margin-left: 4%; }\n"
	"  .column:first-child,\n"
	"  .columns:first-child {\n"
	"    margin-left: 0; }\n"
	"\n"
	"  .one.column,\n"
	"  .one.columns                    { width: 4.66666666667%; }\n"
	"  .two.columns                    { width: 13.3333333333%; }\n"
	"  .three.columns                  { width: 22%;            }\n"
	"  .four.columns                   { width: 30.6666666667%; }\n"
	"  .five.columns                   { width: 39.3333333333%; }\n"
	"  .six.columns                    { width: 48%;            }\n"
	"  .seven.columns                  { width: 56.6666666667%; }\n"
	"  .eight.columns                  { width: 65.3333333333%; }\n"
	"  .nine.columns                   { width: 74.0%;          }\n"
	"  .ten.columns                    { width: 82.6666666667%; }\n"
	"  .eleven.columns                 { width: 91.3333333333%; }\n"
	"  .twelve.columns                 { width: 100%; margin-left: 0; }\n"
	"\n"
	"  .one-third.column               { width: 30.6666666667%; }\n"
	"  .two-thirds.column              { width: 65.3333333333%; }\n"
	"\n"
	"  .one-half.column                { width: 48%; }\n"
	"\n"
	"  /* Offsets */\n"
	"  .offset-by-one.column,\n"
	"  .offset-by-one.columns          { margin-left: 8.66666666667%; }\n"
	"  .offset-by-two.column,\n"
	"  .offset-by-two.columns          { margin-left: 17.3333333333%; }\n"
	"  .offset-by-three.column,\n"
	"  .offset-by-three.columns        { margin-left: 26%;            }\n"
	"  .offset-by-four.column,\n"
	"  .offset-by-four.columns         { margin-left: 34.6666666667%; }\n"
	"  .offset-by-five.column,\n"
	"  .offset-by-five.columns         { margin-left: 43.3333333333%; }\n"
	"  .offset-by-six.column,\n"
	"  .offset-by-six.columns          { margin-left: 52%;            }\n"
	"  .offset-by-seven.column,\n"
	"  .offset-by-seven.columns        { margin-left: 60.6666666667%; }\n"
	"  .offset-by-eight.column,\n"
	"  .offset-by-eight.columns        { margin-left: 69.3333333333%; }\n"
	"  .offset-by-nine.column,\n"
	"  .offset-by-nine.columns         { margin-left: 78.0%;          }\n"
	"  .offset-by-ten.column,\n"
	"  .offset-by-ten.columns          { margin-left: 86.6666666667%; }\n"
	"  .offset-by-eleven.column,\n"
	"  .offset-by-eleven.columns       { margin-left: 95.3333333333%; }\n"
	"\n"
	"  .offset-by-one-third.column,\n"
	"  .offset-by-one-third.columns    { margin-left: 34.6666666667%; }\n"
	"  .offset-by-two-thirds.column,\n"
	"  .offset-by-two-thirds.columns   { margin-left: 69.3333333333%; }\n"
	"\n"
	"  .offset-by-one-half.column,\n"
	"  .offset-by-one-half.columns     { margin-left: 52%; }\n"
	"\n"
	"}\n"
	"\n"
	"\n"
	"/* Base Styles\n"
	"?????????????????????????????????????????????????? */\n"
	"/* NOTE\n"
	"html is set to 62.5% so that all the REM measurements throughout Skeleton\n"
	"are based on 10px sizing. So basically 1.5rem = 15px :) */\n"
	"html {\n"
	"  font-size: 62.5%; }\n"
	"body {\n"
	"  font-size: 1.5em; /* currently ems cause chrome bug misinterpreting rems on body element */\n"
	"  line-height: 1.6;\n"
	"  font-weight: 400;\n"
	"  font-family: \"Raleway\", \"HelveticaNeue\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
	"  color: #222; }\n"
	"\n"
	"\n"
	"/* Typography\n"
	"?????????????????????????????????????????????????? */\n"
	"h1, h2, h3, h4, h5, h6 {\n"
	"  margin-top: 0;\n"
	"  margin-bottom: 2rem;\n"
	"  font-weight: 300; }\n"
	"h1 { font-size: 4.0rem; line-height: 1.2;  letter-spacing: -.1rem;}\n"
	"h2 { font-size: 3.6rem; line-height: 1.25; letter-spacing: -.1rem; }\n"
	"h3 { font-size: 3.0rem; line-height: 1.3;  letter-spacing: -.1rem; }\n"
	"h4 { font-size: 2.4rem; line-height: 1.35; letter-spacing: -.08rem; }\n"
	"h5 { font-size: 1.8rem; line-height: 1.5;  letter-spacing: -.05rem; }\n"
	"h6 { font-size: 1.5rem; line-height: 1.6;  letter-spacing: 0; }\n"
	"\n"
	"/* Larger than phablet */\n"
	"@media (min-width: 550px) {\n"
	"  h1 { font-size: 5.0rem; }\n"
	"  h2 { font-size: 4.2rem; }\n"
	"  h3 { font-size: 3.6rem; }\n"
	"  h4 { font-size: 3.0rem; }\n"
	"  h5 { font-size: 2.4rem; }\n"
	"  h6 { font-size: 1.5rem; }\n"
	"}\n"
	"\n"
	"p {\n"
	"  margin-top: 0; }\n"
	"\n"
	"\n"
	"/* Links\n"
	"?????????????????????????????????????????????????? */\n"
	"a {\n"
	"  color: #1EAEDB; }\n"
	"a:hover {\n"
	"  color: #0FA0CE; }\n"
	"\n"
	"\n"
	"/* Buttons\n"
	"?????????????????????????????????????????????????? */\n"
	".button,\n"
	"button,\n"
	"input[type=\"submit\"],\n"
	"input[type=\"reset\"],\n"
	"input[type=\"button\"] {\n"
	"  display: inline-block;\n"
	"  height: 38px;\n"
	"  padding: 0 30px;\n"
	"  color: #555;\n"
	"  text-align: center;\n"
	"  font-size: 11px;\n"
	"  font-weight: 600;\n"
	"  line-height: 38px;\n"
	"  letter-spacing: .1rem;\n"
	"  text-transform: uppercase;\n"
	"  text-decoration: none;\n"
	"  white-space: nowrap;\n"
	"  background-color: transparent;\n"
	"  border-radius: 4px;\n"
	"  border: 1px solid #bbb;\n"
	"  cursor: pointer;\n"
	"  box-sizing: border-box; }\n"
	".button:hover,\n"
	"button:hover,\n"
	"input[type=\"submit\"]:hover,\n"
	"input[type=\"reset\"]:hover,\n"
	"input[type=\"button\"]:hover,\n"
	".button:focus,\n"
	"button:focus,\n"
	"input[type=\"submit\"]:focus,\n"
	"input[type=\"reset\"]:focus,\n"
	"input[type=\"button\"]:focus {\n"
	"  color: #333;\n"
	"  border-color: #888;\n"
	"  outline: 0; }\n"
	".button.button-primary,\n"
	"button.button-primary,\n"
	"input[type=\"submit\"].button-primary,\n"
	"input[type=\"reset\"].button-primary,\n"
	"input[type=\"button\"].button-primary {\n"
	"  color: #FFF;\n"
	"  background-color: #33C3F0;\n"
	"  border-color: #33C3F0; }\n"
	".button.button-primary:hover,\n"
	"button.button-primary:hover,\n"
	"input[type=\"submit\"].button-primary:hover,\n"
	"input[type=\"reset\"].button-primary:hover,\n"
	"input[type=\"button\"].button-primary:hover,\n"
	".button.button-primary:focus,\n"
	"button.button-primary:focus,\n"
	"input[type=\"submit\"].button-primary:focus,\n"
	"input[type=\"reset\"].button-primary:focus,\n"
	"input[type=\"button\"].button-primary:focus {\n"
	"  color: #FFF;\n"
	"  background-color: #1EAEDB;\n"
	"  border-color: #1EAEDB; }\n"
	"\n"
	"\n"
	"/* Forms\n"
	"?????????????????????????????????????????????????? */\n"
	"input[type=\"email\"],\n"
	"input[type=\"number\"],\n"
	"input[type=\"search\"],\n"
	"input[type=\"text\"],\n"
	"input[type=\"tel\"],\n"
	"input[type=\"url\"],\n"
	"input[type=\"password\"],\n"
	"textarea,\n"
	"select {\n"
	"  height: 38px;\n"
	"  padding: 6px 10px; /* The 6px vertically centers text on FF, ignored by Webkit */\n"
	"  background-color: #fff;\n"
	"  border: 1px solid #D1D1D1;\n"
	"  border-radius: 4px;\n"
	"  box-shadow: none;\n"
	"  box-sizing: border-box; }\n"
	"/* Removes awkward default styles on some inputs for iOS */\n"
	"input[type=\"email\"],\n"
	"input[type=\"number\"],\n"
	"input[type=\"search\"],\n"
	"input[type=\"text\"],\n"
	"input[type=\"tel\"],\n"
	"input[type=\"url\"],\n"
	"input[type=\"password\"],\n"
	"textarea {\n"
	"  -webkit-appearance: none;\n"
	"     -moz-appearance: none;\n"
	"          appearance: none; }\n"
	"textarea {\n"
	"  min-height: 65px;\n"
	"  padding-top: 6px;\n"
	"  padding-bottom: 6px; }\n"
	"input[type=\"email\"]:focus,\n"
	"input[type=\"number\"]:focus,\n"
	"input[type=\"search\"]:focus,\n"
	"input[type=\"text\"]:focus,\n"
	"input[type=\"tel\"]:focus,\n"
	"input[type=\"url\"]:focus,\n"
	"input[type=\"password\"]:focus,\n"
	"textarea:focus,\n"
	"select:focus {\n"
	"  border: 1px solid #33C3F0;\n"
	"  outline: 0; }\n"
	"label,\n"
	"legend {\n"
	"  display: block;\n"
	"  margin-bottom: .5rem;\n"
	"  font-weight: 600; }\n"
	"fieldset {\n"
	"  padding: 0;\n"
	"  border-width: 0; }\n"
	"input[type=\"checkbox\"],\n"
	"input[type=\"radio\"] {\n"
	"  display: inline; }\n"
	"label > .label-body {\n"
	"  display: inline-block;\n"
	"  margin-left: .5rem;\n"
	"  font-weight: normal; }\n"
	"\n"
	"\n"
	"/* Lists\n"
	"?????????????????????????????????????????????????? */\n"
	"ul {\n"
	"  list-style: circle inside; }\n"
	"ol {\n"
	"  list-style: decimal inside; }\n"
	"ol, ul {\n"
	"  padding-left: 0;\n"
	"  margin-top: 0; }\n"
	"ul ul,\n"
	"ul ol,\n"
	"ol ol,\n"
	"ol ul {\n"
	"  margin: 1.5rem 0 1.5rem 3rem;\n"
	"  font-size: 90%; }\n"
	"li {\n"
	"  margin-bottom: 1rem; }\n"
	"\n"
	"\n"
	"/* Code\n"
	"?????????????????????????????????????????????????? */\n"
	"code {\n"
	"  padding: .2rem .5rem;\n"
	"  margin: 0 .2rem;\n"
	"  font-size: 90%;\n"
	"  white-space: nowrap;\n"
	"  background: #F1F1F1;\n"
	"  border: 1px solid #E1E1E1;\n"
	"  border-radius: 4px; }\n"
	"pre > code {\n"
	"  display: block;\n"
	"  padding: 1rem 1.5rem;\n"
	"  white-space: pre; }\n"
	"\n"
	"\n"
	"/* Tables\n"
	"?????????????????????????????????????????????????? */\n"
	"th,\n"
	"td {\n"
	"  padding: 12px 15px;\n"
	"  text-align: left;\n"
	"  border-bottom: 1px solid #E1E1E1; }\n"
	"th:first-child,\n"
	"td:first-child {\n"
	"  padding-left: 0; }\n"
	"th:last-child,\n"
	"td:last-child {\n"
	"  padding-right: 0; }\n"
	"\n"
	"\n"
	"/* Spacing\n"
	"?????????????????????????????????????????????????? */\n"
	"button,\n"
	".button {\n"
	"  margin-bottom: 1rem; }\n"
	"input,\n"
	"textarea,\n"
	"select,\n"
	"fieldset {\n"
	"  margin-bottom: 1.5rem; }\n"
	"pre,\n"
	"blockquote,\n"
	"dl,\n"
	"figure,\n"
	"table,\n"
	"p,\n"
	"ul,\n"
	"ol,\n"
	"form {\n"
	"  margin-bottom: 2.5rem; }\n"
	"\n"
	"\n"
	"/* Utilities\n"
	"?????????????????????????????????????????????????? */\n"
	".u-full-width {\n"
	"  width: 100%;\n"
	"  box-sizing: border-box; }\n"
	".u-max-full-width {\n"
	"  max-width: 100%;\n"
	"  box-sizing: border-box; }\n"
	".u-pull-right {\n"
	"  float: right; }\n"
	".u-pull-left {\n"
	"  float: left; }\n"
	"\n"
	"\n"
	"/* Misc\n"
	"?????????????????????????????????????????????????? */\n"
	"hr {\n"
	"  margin-top: 3rem;\n"
	"  margin-bottom: 3.5rem;\n"
	"  border-width: 0;\n"
	"  border-top: 1px solid #E1E1E1; }\n"
	"\n"
	"\n"
	"/* Clearing\n"
	"?????????????????????????????????????????????????? */\n"
	"\n"
	"/* Self Clearing Goodness */\n"
	".container:after,\n"
	".row:after,\n"
	".u-cf {\n"
	"  content: \"\";\n"
	"  display: table;\n"
	"  clear: both; }\n"
	"\n"
	"\n"
	"/* Media Queries\n"
	"?????????????????????????????????????????????????? */\n"
	"/*\n"
	"Note: The best way to structure the use of media queries is to create the queries\n"
	"near the relevant code. For example, if you wanted to change the styles for buttons\n"
	"on small devices, paste the mobile query code up in the buttons section and style it\n"
	"there.\n"
	"*/\n"
	"\n"
	"\n"
	"/* Larger than mobile */\n"
	"@media (min-width: 400px) {}\n"
	"\n"
	"/* Larger than phablet (also point when grid becomes active) */\n"
	"@media (min-width: 550px) {}\n"
	"\n"
	"/* Larger than tablet */\n"
	"@media (min-width: 750px) {}\n"
	"\n"
	"/* Larger than desktop */\n"
	"@media (min-width: 1000px) {}\n"
	"\n"
	"/* Larger than Desktop HD */\n"
	"@media (min-width: 1200px) {}\n";
const int www_skeleton_css_length = 9624;
